"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createOrder, login, register } from "./lib/api";
const services=[{title:"Yük Taşımacılığı",description:"Şehir içi, şehirler arası ve parsiyel taşımacılık.",icon:"▣"},{title:"Kurye",description:"Motosikletli ve acil teslimat çözümleri.",icon:"↗"},{title:"Acil Yardım",description:"Çekici, akü, lastik, yakıt ve yol yardım desteği.",icon:"!"}];
export default function HomePage(){
 const[pickup,setPickup]=useState(""),[delivery,setDelivery]=useState(""),[serviceType,setServiceType]=useState("Yük Taşımacılığı"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[authMode,setAuthMode]=useState<"login"|"register">("login"),[authenticated,setAuthenticated]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>setAuthenticated(Boolean(window.localStorage.getItem("yuklab_access_token"))),[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{let t=window.localStorage.getItem("yuklab_access_token");if(!t){if(!email||password.length<8)throw new Error("E-posta ve en az 8 karakterli şifre gerekli.");if(authMode==="register"){if(!firstName||!lastName)throw new Error("Ad ve soyad gerekli.");await register({email,password,firstName,lastName});}const r=await login(email,password);t=r.accessToken;window.localStorage.setItem("yuklab_access_token",t);window.localStorage.setItem("yuklab_user_role",r.user.role);setAuthenticated(true);}const r=await createOrder(t,{serviceType,pickupAddress:pickup,deliveryAddress:delivery||undefined});setMessage(`Talebin oluşturuldu. Sipariş no: ${r.order.id.slice(0,8)}`);setPickup("");setDelivery("");}catch(x){setMessage(x instanceof Error?x.message:"Talep oluşturulamadı.");}finally{setBusy(false);}}
 return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">YÜKLAB · SMART LOGISTICS NETWORK</p><h1>Yükünü doğru hizmet sağlayıcıyla buluştur.</h1><p className="lead">Türkiye'den dünyaya ölçeklenmek üzere tasarlanan akıllı lojistik ağı. Taşıma, kurye ve acil yardım ihtiyaçlarını tek noktadan yönet.</p><div className="trust-row"><Link className="nav-link" href="/orders">Siparişlerim →</Link><Link className="nav-link" href="/provider">Provider Hub →</Link></div></div><form className="request-card" onSubmit={submit}><div className="request-heading"><div><span className="mini-label">GERÇEK API AKIŞI</span><h2>Taşıma ihtiyacını oluştur</h2></div><span className="status-dot" aria-label="Sistem hazır"/></div><label>Hizmet<select value={serviceType} onChange={e=>setServiceType(e.target.value)}><option>Yük Taşımacılığı</option><option>Kurye</option><option>Acil Yardım</option></select></label><label>Nereden?<input value={pickup} onChange={e=>setPickup(e.target.value)} placeholder="Pickup adresi" required/></label><label>Nereye?<input value={delivery} onChange={e=>setDelivery(e.target.value)} placeholder="Teslimat adresi"/></label>{!authenticated&&<>{authMode==="register"&&<><label>Ad<input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="Ad" required/></label><label>Soyad<input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Soyad" required/></label></>}<label>E-posta<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ornek@mail.com" required/></label><label>Şifre<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="En az 8 karakter" required/></label><button className="auth-switch" type="button" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Yeni hesap oluştur":"Mevcut hesabımla giriş yap"}</button></>}<button type="submit" disabled={busy}>{busy?"Gönderiliyor…":"Talep oluştur"}<span>→</span></button>{message&&<p className={message.includes("oluşturuldu")?"success":"error"}>{message}</p>}</form></section><section className="services" aria-label="YükLab hizmetleri">{services.map(s=><article className="service-card" key={s.title}><span className="service-icon">{s.icon}</span><h2>{s.title}</h2><p>{s.description}</p></article>)}</section></main>;
}
