"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createOffer, listProviderOffers, listProviderOrders, Offer, Order } from "../lib/api";
export default function ProviderPage() {
 const [orders,setOrders]=useState<Order[]>([]),[offers,setOffers]=useState<Offer[]>([]),[token,setToken]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function load(t:string){const [a,b]=await Promise.all([listProviderOrders(t),listProviderOffers(t)]);setOrders(a.orders);setOffers(b.offers);}
 useEffect(()=>{const t=window.localStorage.getItem("yuklab_access_token")??"";setToken(t);if(t)load(t).catch(e=>setMessage(e instanceof Error?e.message:"Veriler alınamadı."));},[]);
 async function submit(e:FormEvent<HTMLFormElement>,orderId:string){e.preventDefault();if(!token)return;setBusy(orderId);setMessage("");const f=new FormData(e.currentTarget);try{await createOffer(token,orderId,{amountMinor:Number(f.get("amount")),etaMinutes:Number(f.get("eta"))||undefined,note:String(f.get("note")||"").trim()||undefined});await load(token);setMessage("Teklif gönderildi.");e.currentTarget.reset();}catch(x){setMessage(x instanceof Error?x.message:"Teklif gönderilemedi.");}finally{setBusy("");}}
 return <main className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">YÜKLAB · PROVIDER HUB</p><h1>Açık işler</h1><p className="lead">Uygun işleri incele, fiyat ve tahmini varış süresiyle teklif gönder.</p></div><Link className="nav-link" href="/">Müşteri ekranı →</Link></header>{!token?<div className="notice error">Önce müşteri ekranından giriş yapmalısın.</div>:<>{message&&<div className="notice">{message}</div>}<section className="dashboard-grid"><div><h2>Teklif bekleyen işler</h2><div className="stack">{orders.length===0?<div className="empty">Şu anda uygun açık iş yok.</div>:orders.map(o=><article className="job-card" key={o.id}><div className="job-top"><strong>{o.serviceType}</strong><span>{o.status}</span></div><p><b>Alım:</b> {o.pickupAddress}</p><p><b>Teslim:</b> {o.deliveryAddress||"Belirtilmemiş"}</p>{o.budgetMinor&&<p><b>Müşteri bütçesi:</b> {Number(o.budgetMinor)/100} {o.currency}</p>}<form onSubmit={e=>submit(e,o.id)} className="offer-form"><input name="amount" type="number" min="1" placeholder="Teklif (kuruş)" required/><input name="eta" type="number" min="1" placeholder="ETA dakika"/><input name="note" placeholder="Kısa not"/><button disabled={busy===o.id}>{busy===o.id?"Gönderiliyor…":"Teklif ver →"}</button></form></article>)}</div></div><aside><h2>Tekliflerim</h2><div className="stack">{offers.length===0?<div className="empty">Henüz teklif göndermedin.</div>:offers.map(o=><article className="offer-card" key={o.id}><div><strong>{o.order?.serviceType}</strong><span className={`badge ${o.status.toLowerCase()}`}>{o.status}</span></div><p>{Number(o.amountMinor)/100} {o.currency} · {o.etaMinutes?`${o.etaMinutes} dk`:"ETA yok"}</p><small>{o.order?.pickupAddress} → {o.order?.deliveryAddress||"—"}</small></article>)}</div></aside></section></>}</main>;
}
