"use client";
import { useEffect, useState } from "react";
import { acceptOffer, listOrderOffers, listOrders, Offer, Order } from "../lib/api";
export default function OrdersPage(){
 const [token,setToken]=useState(""),[orders,setOrders]=useState<Order[]>([]),[offers,setOffers]=useState<Record<string,Offer[]>>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 async function load(t:string){const r=await listOrders(t);setOrders(r.orders);const entries=await Promise.all(r.orders.map(async o=>[o.id,(await listOrderOffers(t,o.id)).offers] as const));setOffers(Object.fromEntries(entries));}
 useEffect(()=>{const t=window.localStorage.getItem("yuklab_access_token")??"";setToken(t);if(t)load(t).catch(e=>setMessage(e instanceof Error?e.message:"Siparişler alınamadı."));},[]);
 async function choose(orderId:string,offerId:string){if(!token)return;setBusy(offerId);setMessage("");try{await acceptOffer(token,orderId,offerId);await load(token);setMessage("Teklif kabul edildi. Sürücü atandı.");}catch(e){setMessage(e instanceof Error?e.message:"Teklif kabul edilemedi.");}finally{setBusy("");}}
 return <main className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">YÜKLAB · CUSTOMER</p><h1>Siparişlerim</h1><p className="lead">Taleplerini, gelen teklifleri ve seçtiğin hizmet sağlayıcıyı yönet.</p></div><a className="nav-link" href="/">Yeni talep →</a></header>{!token?<div className="notice error">Siparişlerini görmek için giriş yapmalısın.</div>:<>{message&&<div className="notice">{message}</div>}<div className="stack">{orders.length===0?<div className="empty">Henüz sipariş yok.</div>:orders.map(o=><article className="job-card" key={o.id}><div className="job-top"><strong>{o.serviceType}</strong><span>{o.status}</span></div><p><b>{o.pickupAddress}</b> → {o.deliveryAddress||"Teslimat adresi yok"}</p><h3>Teklifler</h3>{(offers[o.id]||[]).length===0?<p>Henüz teklif gelmedi.</p>:(offers[o.id]||[]).map(f=><div className="offer-card" key={f.id}><div><strong>{f.provider?.firstName} {f.provider?.lastName}</strong><span>{f.status}</span></div><p>{Number(f.amountMinor)/100} {f.currency} · {f.etaMinutes?`${f.etaMinutes} dk`:"ETA yok"}</p>{f.note&&<small>{f.note}</small>}{f.status==="PENDING"&&["PUBLISHED","OFFERING"].includes(o.status)&&<button disabled={busy===f.id} onClick={()=>choose(o.id,f.id)}>{busy===f.id?"Seçiliyor…":"Bu teklifi kabul et"}</button>}</div>)}</article>)}</div></>}</main>;
}
